apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serving
  labels:
    app: ml-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-serving
  template:
    metadata:
      labels:
        app: ml-serving
    spec:
      containers:
        - name: ml-serving
          image: ashutosh5786/ml-serving:latest # <- TODO replace this with the actual image URI if using self-created image
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
