apiVersion: v1
kind: Service
metadata:
  name: ml-serving
spec:
  type: LoadBalancer # NOTE Use NodePort for Minikube if LoadBalancer not supported
  selector:
    app: ml-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
